### ISSUE TITLE
c2s visualize does not work

### ISSUE THREAD

**Issue by jonasrauber** [jonasrauber/c2s-docker#3]
``` sh
Traceback (most recent call last):
  File "/usr/local/bin/c2s", line 43, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/c2s", line 38, in main
    return __import__('c2s-{0}'.format(args.command)).main([' '.join(argv[:2])] + argv[2:])
  File "/usr/local/bin/c2s-visualize.py", line 48, in main
    args.height if args.height > 0 else len(data) * 1.5 + .3))
  File "/usr/lib/pymodules/python2.7/matplotlib/pyplot.py", line 423, in figure
    **kwargs)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 79, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/lib/pymodules/python2.7/matplotlib/backends/backend_tkagg.py", line 87, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1767, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable
```

**Comment by jonasrauber** [comment]
Only tested on OS X. Not sure, if it fails on Linux as well.

**Comment by jonasrauber** [comment]
Should try SSH with X11 forwarding.

**Comment by jonasrauber** [comment]
[Sharing the X11 socket](http://stackoverflow.com/questions/25281992/alternatives-to-ssh-x11-forwarding-for-docker-containers) seems to be a really nice solution for this problem. Does not even require ssh.
However, I couldn't test it so far as it does not work on OS X because of boot2docker.

**Comment by jonasrauber** [comment]
There exists a [workaround for OS X](https://github.com/docker/docker/issues/8710), but it requires additional tools.

**Comment by jonasrauber** [comment]
The following steps work on OS X:

``` sh
brew install socat
socat TCP-LISTEN:6000,reuseaddr,fork UNIX-CLIENT:\"$DISPLAY\"
# in another window
docker run -it --rm -e DISPLAY=192.168.1.2:0 -v $PWD:/data/workdir jonasrauber/c2s visualize data.0.mat
```

The ip address 192.168.1.2 needs to be replaced with the respective host ip (i.e. the ip of OS X).
